"""Constants for movie search (API URLs, ISO country map, genre maps)."""

import re

TMDB_BASE = "https://api.tmdb.org/3"


TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p/w342"


TVMAZE_BASE = "https://api.tvmaze.com"


_YEAR_PATTERN = re.compile(r"^(19[0-9]{2}|20[0-9]{2})$")


_ISO2_TO_COUNTRY: dict[str, str] = {
    "US": "United States",
    "CA": "Canada",
    "GB": "United Kingdom",
    "CN": "China",
    "JP": "Japan",
    "KR": "South Korea",
    "FR": "France",
    "DE": "Germany",
    "IN": "India",
    "AU": "Australia",
    "BR": "Brazil",
    "IT": "Italy",
    "ES": "Spain",
    "RU": "Russia",
    "SE": "Sweden",
    "DK": "Denmark",
    "NO": "Norway",
    "NL": "Netherlands",
    "BE": "Belgium",
    "CH": "Switzerland",
    "AT": "Austria",
    "PL": "Poland",
    "TR": "Turkey",
    "MX": "Mexico",
    "AR": "Argentina",
    "CO": "Colombia",
    "CL": "Chile",
    "TH": "Thailand",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "SG": "Singapore",
    "NZ": "New Zealand",
    "ZA": "South Africa",
    "IL": "Israel",
    "IE": "Ireland",
    "PT": "Portugal",
    "GR": "Greece",
    "CZ": "Czech Republic",
    "HU": "Hungary",
    "RO": "Romania",
    "UA": "Ukraine",
    "FI": "Finland",
    "IS": "Iceland",
    "PH": "Philippines",
    "ID": "Indonesia",
    "MY": "Malaysia",
    "VN": "Vietnam",
    "EG": "Egypt",
    "NG": "Nigeria",
    "KE": "Kenya",
    "MA": "Morocco",
    "IR": "Iran",
    "SA": "Saudi Arabia",
    "AE": "United Arab Emirates",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "PE": "Peru",
    "VE": "Venezuela",
    "CU": "Cuba",
    "HR": "Croatia",
    "RS": "Serbia",
    "BG": "Bulgaria",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "LT": "Lithuania",
    "LV": "Latvia",
    "EE": "Estonia",
    "LU": "Luxembourg",
    "GE": "Georgia",
    "LB": "Lebanon",
    "JO": "Jordan",
    "QA": "Qatar",
    "PR": "Puerto Rico",
    "CR": "Costa Rica",
    "PA": "Panama",
    "UY": "Uruguay",
    "MM": "Myanmar",
    "KH": "Cambodia",
    "NP": "Nepal",
    "LK": "Sri Lanka",
    "MN": "Mongolia",
    "KZ": "Kazakhstan",
    "DZ": "Algeria",
    "TN": "Tunisia",
    "ET": "Ethiopia",
    "GH": "Ghana",
    "TZ": "Tanzania",
}


_TMDB_GENRE_MAP: dict[int, str] = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Sci-Fi",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western",
}


_TMDB_TV_GENRE_MAP: dict[int, str] = {
    10759: "Action & Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    10762: "Kids",
    9648: "Mystery",
    10763: "News",
    10764: "Reality",
    10765: "Sci-Fi & Fantasy",
    10766: "Soap",
    10767: "Talk",
    10768: "War & Politics",
    37: "Western",
}


