# Re-exports from db and schemas submodules.
# Existing code can still `from models import UserRecord, ...`

from models.db import (
    UserRecord,
    MediaItemRecord,
    SessionRecord,
    RecommendationRecord,
    OperationLogRecord,
    PlaylistRecord,
    PlaylistItemRecord,
    MediaServerRecord,
    MoviePilotRecord,
)

from models.schemas import (
    LoginRequest,
    LoginResponse,
    CreateUserRequest,
    UserInfo,
    ChangePasswordRequest,
    MediaRating,
    WishlistItem,
    WishlistData,
    MarkAsWatchedRequest,
    MediaData,
    StrategyParams,
    RecommendationRequest,
    MediaRecommendation,
    RecommendationResponse,
    ConversationMessage,
    FollowUpRequest,
    PlaylistCreate,
    PlaylistUpdate,
    PlaylistItemInput,
    PlaylistItemUpdate,
    PlaylistReorderRequest,
    PlaylistAINameRequest,
    PlaylistCategorizeRequest,
    PlaylistCompleteRequest,
)

__all__ = [
    "UserRecord",
    "MediaItemRecord",
    "SessionRecord",
    "RecommendationRecord",
    "OperationLogRecord",
    "MediaServerRecord",
    "MoviePilotRecord",
    "LoginRequest",
    "LoginResponse",
    "CreateUserRequest",
    "UserInfo",
    "ChangePasswordRequest",
    "MediaRating",
    "WishlistItem",
    "WishlistData",
    "MarkAsWatchedRequest",
    "MediaData",
    "StrategyParams",
    "RecommendationRequest",
    "MediaRecommendation",
    "RecommendationResponse",
    "ConversationMessage",
    "FollowUpRequest",
    "PlaylistCreate",
    "PlaylistUpdate",
    "PlaylistItemInput",
    "PlaylistItemUpdate",
    "PlaylistReorderRequest",
    "PlaylistAINameRequest",
    "PlaylistCategorizeRequest",
    "PlaylistCompleteRequest",
]
